### ISSUE TITLE
Addon does not work with ember-cli 3.4.0-beta.2 or above; `NODE_ENV is not defined`

### ISSUE THREAD

**Issue by Krzyrok** [healthsparq/ember-cli-prop-types#16]
Hello!

## Summary
ember-cli-prop-types does not work with ember-cli 3.4.0-beta.2 or above.

## Description + Repro Steps
I tried to update ember-cli (either only ember-cli or using ember-cli-update [which updates more dependencies]) to the newest version (3.4.3). But after update, I see an error in my app:  `ReferenceError: NODE_ENV is not defined`.

```
Uncaught ReferenceError: NODE_ENV is not defined
    at Object.initialize (component-prop-types.js:21)
    at index.js:91
    at Vertices.each (dag-map.js:188)
    at Vertices.walk (dag-map.js:117)
    at DAG.each (dag-map.js:62)
    at DAG.topsort (dag-map.js:68)
    at Class._runInitializer (index.js:112)
    at Class.runInitializers (index.js:88)
    at Class._bootSync (application.js:431)
    at Class.domReady (application.js:385)
```

ember-cli version 3.3.0 or 3.4.0-beta.1 works correctly. ember-cli 3.4.0-beta.2 or 3.4.2 or above does not work with ember-cli-prop-types

It looks that `NODE_ENV`, `INCLUDE_GET_DEFAULT_PROPS` and other variables are not replaced by `babel-plugin-inline-replace-variables` after `ember-cli` upgrade.
If I moved configuration of `babel-plugin-inline-replace-variables` from `preprocessTree` to the `options` object (like in the example in the `babel/ember-cli-babel` https://github.com/babel/ember-cli-babel#options ), then problem disappeared. Of course - `env` or `process.env.EMBER_ENV` is not defined yet. But also helped moving this configuration from `preprocessTree` to the `included` function (I guess that order of called functions was changed in new ember - it's only my guess).

## Environment Information
Here's my setup:

- OS: Antergos running version 4.18.12-arch1-1-ARCH
- ember-cli: 3.4.3
- ember-cli-prop-types: 1.5.0
- Node: 10.11.0 with npm 6.4.1, yarn 1.9.4, bower 1.8.4
- Browser: Chrome 69.0.3497.100-1

**Comment by evrowe** [comment]
Hey @Krzyrok! Thanks for reporting this. Since you've been able to arrive at a solution with relatively minimal changes, would you be open to making a PR to get those in place?

**Comment by Krzyrok** [comment]
Sorry for the delayed response. Yes, I'll make PR ASAP

**Comment by ghost** [comment]
Hi, any update about this issue? I am currently trying to update ember-cli to version 3.4.1 or above.

Thank you!

**Comment by Krzyrok** [comment]
Hi, sorry for delay. I've forked and pushed the changes - so waiting for merge and release only.

**Comment by evrowe** [comment]
[Version 1.6.0 has been published](https://www.npmjs.com/package/ember-cli-prop-types/v/1.6.0), which includes these fixes. Big thanks to @Krzyrok for getting things working with newer versions of Ember CLI!
