### ISSUE TITLE
Uncaught ReferenceError: DEVELOPMENT is not defined

### ISSUE THREAD

**Issue by cah-danmonroe** [healthsparq/ember-cli-prop-types#3]
## Summary

With a new Ember app and installing ember-cli-prop-types, I get an error in the console `Uncaught ReferenceError: DEVELOPMENT is not defined` and the app will not load.

>ember-cli: 2.13.1
node: 6.10.2
os: darwin x64

`>ember new prop-types-test`
`>ember serve `- app loads as expected
`>ember install ember-cli-prop-types`
`>ember serve` - error

**Comment by evrowe** [comment]
Thanks, Dan! I'm investigating now.

**Comment by evrowe** [comment]
@cah-danmonroe Great news, this is actually already resolved in 1.2.0, which is releasing this morning. Cheers!

**Comment by cah-danmonroe** [comment]
Confirmed, thanks!
